### ISSUE TITLE
Incomplete Crafting Recipe

### ISSUE THREAD

**Issue by Chribit** [deli73/simple-crates#11]
When using roughly enough items, the crafting recipe of a crate does not include logs and just one chain in each corner.

![image](https://user-images.githubusercontent.com/29504473/168819757-02fa75ac-e662-4e34-ab06-0f57b8c1a84d.png)

**Comment by deli73** [comment]
the recipe uses tags for the logs; if REI can't handle a basic recipe feature then that's not our problem.

**Comment by Chribit** [comment]
The issue doesn't seem to be REI, it doesn't work with normal crafting either...

![Uploading Capture.JPG…]()

**Comment by Chribit** [comment]
It isn't an issue with REI after all.

I tried fixing the recipe with a datapack, but it seems like the recipe is hardcoded into the mod and overwrites anything external.

**Comment by deli73** [comment]
the recipe is part of an internal datapack, and it works fine in the recipe book. the json is right here. https://github.com/deli73/simple-crates/blob/1.18/src/main/resources/data/simplecrates/recipes/crate.json

if you're convinced the issue is not REI (and we encourage you to try crafting it manually; the blank slots around the outside take logs), we're gonna need more information. if there's an acutal problem besides REI integration we'll look into fixing it.

**Comment by Chribit** [comment]
In know, i unpacked the jar and copy pasted the recipe data into my own datapack… which should be loaded after everything else, right?

And that doesn‘t change that recipe for some reason.

I tried verifying the datapack recipe with manual crafting and it still only allows the four chains. Adding the logs results in nothing.

**Comment by deli73** [comment]
wait, it breaks the actual recipe itself??
what version are you using this on? what other mods do you have?
we have verified that the recipe works normally, our only conclusion is that another mod you're using breaks it somehow

**Comment by Chribit** [comment]
Yeah, it probably is a mod compat issue… but it‘s not because some other crafting recipe is overwriting the crate - then that other item would just be the result.

I‘m playing on the newest fabric version for minecraft 1.18.2.

It‘s quite an extensive list of mods tbh (170+ i think), shall i send you a list? I can order it by function (performance, world gen, equipment, building, etc.)…

**Comment by deli73** [comment]
honestly we don't have the time to sift through a mod list of that size for potential candidates. this is likely an issue that affects other recipes as well; there is nothing remotely unusual about our recipe, so unless you can find proof that one partiuclar mod is incompatible with this mod _specifically_, it's categorically not our problem.

**Comment by Chribit** [comment]
understandable.

I may get back to you if I find something.
